// vite-profile/src/App.tsx
import './style.css';
import { useState } from 'react';
import { CustomProps, ParcelConfig, ParcelProps } from 'single-spa';
import Parcel from 'single-spa-react/parcel'
import {getProfileDetails, Profile} from '@acc/api';

export default function Root(props:any) {
  const [isLoading, setLoading] = useState<Boolean>(false);
  const [data, setData] = useState<Profile>(null);

  const onFetchDetails = async ()=>{
    setLoading(true);
    setTimeout(async ()=>{
      //set time out added to get the loading effects 
      const profileData = await getProfileDetails("https://reqres.in/api/users/5");
      setData(profileData.data);
      setLoading(false);
    },500);  
  }

  const ParcelComponent = (): ParcelConfig<{}>=>{
    return System.import("@acc/helpdesk") as unknown as ParcelConfig<{}>;
  }

  return (
    <div id="profile">
      <h1> Profile React Application </h1>
      {
        (data===null && !isLoading ) ?     
          <div id="detailsBtn">
            <button onClick={onFetchDetails}>Load Profile Details</button>
            <label id="value" >  (The details will be fetched from Utility Microfrontend)</label>
          </div>
        :
        <div>
          {
          isLoading?
          <div id="loader"></div>
          :
            <div>
                <div id="detailSection">
                  <img src={data.avatar} />
                </div>
                <div id="detailSection">
                <label id="field">Name:
                  </label>
                  <label id="value">
                  {data.first_name} {data.last_name}
                  </label>
                </div>
                <div id="detailSection">
                  <label id="field">Email:</label> 
                  <label id="value">{data.email}</label>
                </div>
                <div id="detailSection">
                  <a href='/address'>Go to Address Page </a>
              </div>
           </div>  
          }
        </div>
      }

      <Parcel
        config={ParcelComponent()}
        initiator= {"Profile Application"}
        wrapWith='div'
        wrapStyle={{position:'absolute', bottom:20, right:20}}
       />
      
    </div>
);
}

// address-vue/src/App.vue
<script>
import './style.css'
import Parcel from 'single-spa-vue/parcel'
import { mountRootParcel } from 'single-spa'
export default {
  components: {
    Parcel
  },
  data() {
    return {
      parcelConfig: System.import("@acc/helpdesk"),
      mountParcel: mountRootParcel,
      wrapWith: 'div',
      wrapStyle: {
        position:'absolute',
        bottom:0,
        right:0
      }
    }
  },
  methods: {
    // These are the props passed into the parcel
    getParcelProps() {
      return {
        initiator: `Address Vue Application`
      }
    },
    // Parcels mount asynchronously, so this will be called once the parcel finishes mounting
    parcelMounted() {
      console.log("parcel mounted");
    },
    parcelUpdated() {
      console.log("parcel updated");
    }
  }
}
</script>
<template>
   <div>
    <h2>Address Application In the VueJS Framework</h2>
    <a href="/orders" >
        Load Orders Page
      </a>
    <div>
      <Parcel
        v-on:parcelMounted="parcelMounted()"
        v-on:parcelUpdated="parcelUpdated()"
        :config="parcelConfig"
        :mountParcel="mountParcel"
        :wrapWith="wrapWith"
        :wrapClass="wrapClass"
        :wrapStyle="wrapStyle"
        :parcelProps="getParcelProps()"
      />
    </div>
  </div>

</template>
