// address-vue/src/App.vue
<script>
import './style.css'
import Parcel from 'single-spa-vue/parcel'
import { mountRootParcel } from 'single-spa'
export default {
  components: {
    Parcel
  },
  data() {
    return {
      parcelConfig: System.import("@acc/helpdesk"),
      mountParcel: mountRootParcel,
      wrapWith: 'div',
      wrapStyle: {
        position:'absolute',
        bottom:0,
        right:0
      }
    }
  },
  methods: {
    // These are the props passed into the parcel
    getParcelProps() {
      return {
        initiator: `Address Vue Application`
      }
    },
    // Parcels mount asynchronously, so this will be called once the parcel finishes mounting
    parcelMounted() {
      console.log("parcel mounted");
    },
    parcelUpdated() {
      console.log("parcel updated");
    }
  }
}
</script>
<template>
   <div>
    <h2>Address Application In the VueJS Framework</h2>
    <a href="/orders" >
        Load Orders Page
      </a>
    <div>
      <Parcel
        v-on:parcelMounted="parcelMounted()"
        v-on:parcelUpdated="parcelUpdated()"
        :config="parcelConfig"
        :mountParcel="mountParcel"
        :wrapWith="wrapWith"
        :wrapClass="wrapClass"
        :wrapStyle="wrapStyle"
        :parcelProps="getParcelProps()"
      />
    </div>
  </div>

</template>

// vite-orders/src/App.tsx
import Parcel from 'single-spa-react/parcel'
import './App.css'

function App() {

  return (
    <>
      <div>
      <h1> Order app </h1>
      <section>The Order component is loaded.</section>
      <div>
        <a href='/profile'>Go to Profile</a>
      </div>
      <Parcel
        config={()=>System.import("@acc/helpdesk")}
        initiator= {"Order Application"}
        wrapWith='div'
        wrapStyle={{position:'absolute', bottom:20, right:20}}
       />
    </div>
    </>
  )
}

export default App
